// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_gc4CuVhgqFu8fIhUBfdy4xEY3t5Kqgg',
    appId: '1:1064099031126:web:816b95eb1e1b7fa4f733f7',
    messagingSenderId: '1064099031126',
    projectId: 'moneytrail-b1f88',
    authDomain: 'moneytrail-b1f88.firebaseapp.com',
    storageBucket: 'moneytrail-b1f88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVXL3sOWDMCZEWFZxbGTCTgPBVvbue1nQ',
    appId: '1:1064099031126:android:21863fa3b9a4aa9cf733f7',
    messagingSenderId: '1064099031126',
    projectId: 'moneytrail-b1f88',
    storageBucket: 'moneytrail-b1f88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgHwmWUI8-C7-ZMxyRrZd9BIqffkZQoV8',
    appId: '1:1064099031126:ios:233b2be0c1748f43f733f7',
    messagingSenderId: '1064099031126',
    projectId: 'moneytrail-b1f88',
    storageBucket: 'moneytrail-b1f88.firebasestorage.app',
    iosBundleId: 'com.example.moneytrail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgHwmWUI8-C7-ZMxyRrZd9BIqffkZQoV8',
    appId: '1:1064099031126:ios:233b2be0c1748f43f733f7',
    messagingSenderId: '1064099031126',
    projectId: 'moneytrail-b1f88',
    storageBucket: 'moneytrail-b1f88.firebasestorage.app',
    iosBundleId: 'com.example.moneytrail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_gc4CuVhgqFu8fIhUBfdy4xEY3t5Kqgg',
    appId: '1:1064099031126:web:edd8f214da9c2405f733f7',
    messagingSenderId: '1064099031126',
    projectId: 'moneytrail-b1f88',
    authDomain: 'moneytrail-b1f88.firebaseapp.com',
    storageBucket: 'moneytrail-b1f88.firebasestorage.app',
  );
}
